version: "1.0.0"

services:
  database:
    build:
      context: ./db/config
      dockerfile: DockerFile
    environment:
      POSTGRES_DB: ponto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/var/log/postgresql
    networks:
      - ponto

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - ponto

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sergipetec.org.br
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - ponto

volumes:
  logs:
  data:
  redis:
  pgadmin:

networks:
  ponto:
    driver: bridge
