# Use a imagem oficial do PostgreSQL
FROM postgres:alpine

# Adicione configurações ao arquivo postgresql.conf
RUN echo "log_statement = 'all'" >> /usr/local/share/postgresql/postgresql.conf.sample && \
    echo "logging_collector = on" >> /usr/local/share/postgresql/postgresql.conf.sample && \
    echo "log_directory = '/var/log/postgresql'" >> /usr/local/share/postgresql/postgresql.conf.sample && \
    echo "log_filename = 'postgresql.log'" >> /usr/local/share/postgresql/postgresql.conf.sample

# Exemplo: instale extensões ou faça outras personalizações, se necessário
RUN apk --no-cache add postgresql-contrib

# Diretório para armazenar dados persistentes
VOLUME ["/var/lib/postgresql/data", "/var/log/postgresql"]

# CMD padrão fornecido pela imagem oficial do PostgreSQL
CMD ["postgres", "-c", "config_file=/usr/local/share/postgresql/postgresql.conf.sample"]
