name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: List files
        run: ls

      - name: Navigate to the directory
        run: cd /backend

      - name: List files
        run: ls

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: npm run test
