name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: List files
        run: ls

      - name: Navigate to the directory
        run: |
          cd backend/ && pwd
          if [ $? -eq 0 ]; then
            echo "Sucesso ao navegar para o diretorio 'backend'."
          else
            echo "Falha ao navegar para o diretorio 'backend'."
            exit 1
          fi

      - name: List files
        run: ls

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: npm run test
