name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        run: git clone ${{ github.repository }} --depth=1

      - name: Navigate to the directory
        run: cd backend

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: npm run test
